// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: h8pdmdKq58xaRhHHLoUNc6
// Component: pNbDNQdpNH
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_tag_window_extension.module.css"; // plasmic-import: h8pdmdKq58xaRhHHLoUNc6/projectcss
import sty from "./PlasmicToolTipFrame.module.css"; // plasmic-import: pNbDNQdpNH/css

export type PlasmicToolTipFrame__VariantMembers = {};

export type PlasmicToolTipFrame__VariantsArgs = {};
type VariantPropType = keyof PlasmicToolTipFrame__VariantsArgs;
export const PlasmicToolTipFrame__VariantProps = new Array<VariantPropType>();

export type PlasmicToolTipFrame__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicToolTipFrame__ArgsType;
export const PlasmicToolTipFrame__ArgProps = new Array<ArgPropType>("children");

export type PlasmicToolTipFrame__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultToolTipFrameProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicToolTipFrame__RenderFunc(props: {
  variants: PlasmicToolTipFrame__VariantsArgs;
  args: PlasmicToolTipFrame__ArgsType;
  overrides: PlasmicToolTipFrame__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(projectcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: null,
        value: args.children,
        className: classNames(sty.slotTargetChildren)
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicToolTipFrame__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicToolTipFrame__VariantsArgs;
    args?: PlasmicToolTipFrame__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicToolTipFrame__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicToolTipFrame__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicToolTipFrame__ArgProps,
      internalVariantPropNames: PlasmicToolTipFrame__VariantProps
    });

    return PlasmicToolTipFrame__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicToolTipFrame";
  } else {
    func.displayName = `PlasmicToolTipFrame.${nodeName}`;
  }
  return func;
}

export const PlasmicToolTipFrame = Object.assign(
  // Top-level PlasmicToolTipFrame renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicToolTipFrame
    internalVariantProps: PlasmicToolTipFrame__VariantProps,
    internalArgProps: PlasmicToolTipFrame__ArgProps
  }
);

export default PlasmicToolTipFrame;
/* prettier-ignore-end */
